С-9-1. вынос запросов на уровень репозитория и добавление проверки в …
TaskServiceManager/TSM-base pull request #54
Opened 2022-07-23 15:03 UTC by AleksandrTimonin

…сервис временных отметок

2022-07-24 17:36 UTC, sosulka7 approved these changes
тока конфликт небольшой

2022-07-24 20:06 UTC, itananina requested changes

2022-07-24 20:06 UTC, itananina commented on core-service/src/main/java/com/sanjati/core/repositories/TimePointRepository.java
> +    public Integer checkByExecutorIdAndStatus(Long  executorId, TimePointStatus status);
jpa сама умеет каунты считать, тут можно не прописывать квери
Long countByExecutorIdAndStatus(Long executorId, TimePointStatus status);

2022-07-24 20:06 UTC, itananina commented on core-service/src/main/java/com/sanjati/core/repositories/TimePointRepository.java
> +    public Integer checkCountTimePoints(Long taskId);
а тут не сможет тк в TimePoint нет поля taskId, @Query оставляем

2022-07-24 20:06 UTC, itananina commented on core-service/src/main/java/com/sanjati/core/repositories/TaskRepository.java
> +    public Integer checkCountByOwnerIdAndTaskId(Long taskId, Long id);
можно count (t)>0 как ты предлагал

2022-07-24 20:06 UTC, itananina commented on core-service/src/main/java/com/sanjati/core/services/TimePointService.java
>              if (tp.getStatus().equals(TimePointStatus.FINISHED)){
тут сравниваем через ==

2022-07-24 20:06 UTC, itananina commented on core-service/src/main/java/com/sanjati/core/repositories/TimePointRepository.java
> +    public Integer checkCountTimePoints(Long taskId);
тока подпиши пж поконкретнее типа countByTaskId (слово таймпоинт можно не упоминать тк каунтим через TimePointRepository)

2022-07-24 20:06 UTC, itananina commented on core-service/src/main/java/com/sanjati/core/services/TimePointService.java
> +                taskService.changeStatus(taskId, TaskStatus.ACCEPTED.name());
предлагаю в taskService перегрузить метод - добавить сигнатуру с (Long taskId, TaskStatus status), чтобы сервис сам доставал стрингу из енума, а то в глаза бросается

2022-07-24 20:06 UTC, itananina commented on core-service/src/main/java/com/sanjati/core/services/TimePointService.java
> +                taskService.changeStatus(taskId, TaskStatus.ACCEPTED.name());
мб стоит проверять не по наличию таймпоинтов, а просто проверять статус таски - если не в работе, то сделать в работе. мне кажется, менеджер может возвращать задачу из статуса "Утверждается" в статус "Назначена", чтобы сотрудники видели, что чето новое делать надо - вот в этом случае таймпоинты уже будут, а таска не в работе

2022-07-25 09:33 UTC, AleksandrTimonin commented on core-service/src/main/java/com/sanjati/core/services/TimePointService.java
> +                taskService.changeStatus(taskId, TaskStatus.ACCEPTED.name());
менеджер должен сменить статус на назначено, я сделаю доп проверку на статус назначено и тогда наверно не надо будет дёргать каунт

2022-07-25 19:07 UTC, itananina requested changes

2022-07-25 19:07 UTC, itananina commented on core-service/src/main/java/com/sanjati/core/repositories/TaskRepository.java
> +    public boolean isCountMoreThanZeroByOwnerIdAndTaskId(Long taskId, Long id);
нашла штуку без @Query - existsByIdAndOwnerId

2022-07-25 19:07 UTC, itananina commented on core-service/src/main/java/com/sanjati/core/controllers/TaskController.java
> +
не запускал после исправления?  на 118 строчке тут сломалось

2022-07-25 19:07 UTC, itananina commented on core-service/src/main/java/com/sanjati/core/controllers/TaskController.java
> +
и path сломался

2022-07-25 19:07 UTC, itananina commented on core-service/src/main/java/com/sanjati/core/services/TaskService.java
> +    public void changeStatus(Long id, TaskStatus status) {
в связи со сменой сигнатуры есть лишние шаги в методе, например на 45 строке поиск енума из строки

2022-07-25 19:07 UTC, itananina commented on core-service/src/main/java/com/sanjati/core/controllers/TaskController.java
> +
+ видимо нужен какой-то маппер, чтобы передаваемую в сервис строку преобразовать в енум... короче решение не рабочее совсем

2022-07-25 19:11 UTC, AleksandrTimonin commented on core-service/src/main/java/com/sanjati/core/controllers/TaskController.java
> +
Запускалось...

2022-07-25 19:29 UTC, itananina approved these changes

2022-07-25 19:29 UTC, merged