Feature/с 7 3 на бэке проверять время при активации задачи
TaskServiceManager/TSM-base pull request #78
Opened 2022-08-07 01:41 UTC by white-gray

Не смог придумать как получить _startWorkTime_ и _endWorkTime_ для конкретного executor, поэтому указано некое "общее рабочее время".
Конечно - лажа, но как правильно ?

2022-08-07 17:26 UTC, itananina requested changes

2022-08-07 17:26 UTC, itananina commented on core-service/src/main/java/com/sanjati/core/services/TaskService.java
> +                    }
тут надо рабочее время конкретного сотрудника проверять, оно хранится в полях startWorkTime, endWorkTime

2022-08-08 05:45 UTC, white-gray commented on core-service/src/main/java/com/sanjati/core/services/TaskService.java
> +                    }
не могу придумать как привязаться к пользователю (себе) . Из **_task_** по **_taskId_** я могу получить список executors. Но как узнать кто из них я ? 
Уже пару дней-ночей "пожевываю" в св.время....

2022-08-08 13:41 UTC, AleksandrTimonin reviewed
просмотрел

2022-08-09 20:50 UTC, closed without merging